### PR TITLE
Add multiarch, Dockerhub autobuild, and manifest creation.

### PR DESCRIPTION
**Pull request by tempestnano**
I finally worked out the kinks, and I can confirm it works as expected on amd64 and arm32v7 architectures. I assume arm64v8 will work as well, as it builds and is practically identical. It is setup, so Dockerhub can autobuild and push all architectures to the latest and dev tags.

The post_push manifest creation should fail for the first builds, as I think the tags (amd64 arm32v7 and arm64v8) for each architecture need to be created before the manifest operation can complete successfully.

### CODE REVIEW

**Comment by tempestnano** [comment]
Let me know if you have an issue getting dockerhub to cooperate.
You will now be able to just pull deezloaderremix:latest for all supported architectures.

**Comment by Bockiii** [comment]
Okay, since I've never used the manifest things: If I merge this, what will I have to do on dockerhub?

**Comment by Bockiii** [comment]
So the "latest" build succeeded with 
`Executing post_push hook...
PLATFORMS-ARCH: linux/Dockerfile
Building Dockerfile image natively; No manifest needed for current arch.
Build finished`

while the dev branch (I created a new "dev" tag to replace the "latest-dev" tag) fails:
`Executing post_push hook...
PLATFORMS-ARCH: linux/dev
docker manifest (not working with autobuild on docker hub)
manifest-tool
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 615 0 615 0 0 1635 0 --:--:-- --:--:-- --:--:-- 1635
0 11.8M 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 11.8M 100 11.8M 0 0 10.7M 0 0:00:01 0:00:01 --:--:-- 35.4M
time="2019-12-11T22:45:10Z" level=fatal msg="Inspect of image \"bocki/deezloaderrmx:amd64\" failed with error: manifest unknown: manifest unknown"
post_push hook failed! (1)`

Anything I need to do?

**Comment by tempestnano** [comment]
Setup your auto build rules like so. Also, you may have to simply build them a second time, since the first time it fails (since the manifest tools doesn't see all the images on Dockerhub yet that are called for).

dockerdeez

**Comment by tempestnano** [comment]
The last two dockerfiles are cut off. They should be the full filesnames of the docker files "Dockerfile.dev.arm64v8" and arm32v7.

**Comment by tempestnano** [comment]
In retrospect, I should have included this screenshot in the pull request.

**Comment by tempestnano** [comment]
You will see the final tag structure you should get on the dockerhub repo compiled from my fork:  https://hub.docker.com/r/jstrader/deezloadermx/tags
Post_push will error out (but still the individual build tag will populate on the tags page) until everything has been built once, so it can pull from all the other tags to build the "latest" and "dev" meta-tags.

**Comment by Bockiii** [comment]
I've set up everything and it's building. I will trigger another build tomorrow so that the tags clean up :)

**Comment by tempestnano** [comment]
I have pulled bocki/deezloaderrmx:latest on my rpi4 (arm32v7), and it works like a charm. Thanks Bockiii! Can I just say that the switching between the number if i's in your handle does my head in. Now to solve the reverse proxy business.

**Comment by Bockiii** [comment]
Hehe, yeah, sadly there was already a Bocki here on github :)

So I'm currently building all the things again. It looks like there is either a general network issue with docker hub or that the dev.arm64v8 has an issue.


`Step 11/14 : RUN yarn install && yarn cache clean
---> Running in 2e8d2692fb2a
yarn install v1.16.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/app-builder-lib/-/app-builder-lib-20.44.4.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/deezloaderremix/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Removing intermediate container 2e8d2692fb2a
The command '/bin/sh -c yarn install && yarn cache clean' returned a non-zero code: 1`

Those network connection issues were on every dev.arm64 build so far. Not on the others though.

Trying again

**Comment by tempestnano** [comment]
My dev.arm64v8 built 2 hours ago, and they have identical Dockerfiles. Mine may have succeeded by using Dockerhub's cache. I suspect it is just an intermittent problem with yarnpkg.com. I'll retry with caching disabled.

**Comment by Bockiii** [comment]
Looks good, it's building all now, without any change. So yeah, looks like it was an issue with yarn.

**Comment by Bockiii** [comment]
Finally all done. I will change the dev-versions to port 1731 when I'm home, delete the old dev branch, update the documentation and then post the update in reddit etc.

Thanks a lot!

as for the reverse proxy: What do you mean?

**Comment by tempestnano** [comment]
Per #7 
So one can access the server's web interface from a regular web interface.. https://somedomain.org/deezloaderrmx
I can get everything to come up, but the actual downloading fails (something about the socket.io stuff). Perhaps a subdomain approach will work. https://deez.somedomain.org

**Pull request merged**
