### PR TITLE
Only for discussion

### PR DESCRIPTION
**Pull request by Bockiii**
Hi tempestnano,

the "issues" function is not enabled on your fork, so I didn't know how else to contact you. So ignore the actual content of the pr.

Are you planning on creating a Pull request for the arm versions back into my repo when you are done developing? I saw that you created your own container and would of course be happier if you integrate the arm version into my docker hub container so we can provide both architectures from the same container.

Otherwise it's a useless split and also we could leverage the reach of my container to elevate the arm version usage.

Thanks!

### CODE REVIEW

**Comment by Bockiii** [comment]
pinging @tempestnano  if it wasn't done by creating the pr.

**Comment by tempestnano** [comment]
I didn't realize that it wasn't enabled. I indeed am planning a pull request, but I have one issue to iron out where the dockerized version doesn't download properly. Since I have everything autobuilt and tagged by Dockerhub, there is no way to test the build system without forking.

**Comment by tempestnano** [comment]
Have you encountered the error: "Error: ReferenceError: URL is not defined" when trying to download? I only get this when I am running the dockerized version. It seems fine when installing manually in an alpine image.

**Comment by Bockiii** [comment]
Sounds great!

No, haven't seen that error. Does it occur on the wget command? 

I found some things that see an old node version as a possible culprit if it occurs in there. Which nodejs version does the arm version install?

**Comment by Bockiii** [comment]
Also, did you see issue #3 ? A rasp version was already tried.

There was also a request for an arm version that was kinda ambigously answered on their repo:
https://github.com/RemixDev/DRemixIssues/issues/42

**Comment by tempestnano** [comment]
Thanks! Turns out my problem related to choosing the wrong version of the Alpine base image. They are all harmonized in the other pull request.
I did see #3. It used a Ubuntu base, and I wanted to start from scratch to ensure that all architectures were as close to the same as possible. Also, better image size with Alpine.  It works like a charm on my rpi4 now.

**Comment by tempestnano** [comment]
Regarding the ambiguous answer referenced, iirc they suggest we do exactly what your docker container does (rather than compile an arm standalone desktop app) I think at least.

**Pull request closed without merging**
